baseURL = "https://blog.nimplex.xyz/"
languageCode = "pl-PL"
theme = "terminal"
pagerSize = 5

defaultContentLanguage = "pl"
defaultContentLanguageInSubdir = true

summaryLength = 20
showFullContent = false

[params]
math = true

# dir name of your main content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "posts"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 2

# show selector to switch language
showLanguageSelector = true 

# set theme to full screen width
fullWidthTheme = false

# center theme with default width
centerTheme = true

# if your resource directory contains an image called `cover.(jpg|png|webp)`,
# then the file will be used as a cover automatically.
# With this option you don't have to put the `cover` param in a front-matter.
autoCover = false

# set post to show the last updated
# If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
showLastUpdated = false

# Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
# updatedDatePrefix = "Updated"

# whether to show a page's estimated reading time
readingTime = true

# whether to show a table of contents
# can be overridden in a page's front-matter
Toc = false # default

[[params.sponsors]]
url = "https://mikr.us"
cover = "/mikrus-sponsor.png"

# DEUTSCH
[languages.de]
languageCode = "de-DE"
languageName = "ðŸ‡©ðŸ‡ª Deutsch"
title = "ZSM-Sat Team"
weight = 3

[languages.de.params]
subtitle = ""
owner = ""
keywords = ""
copyright = ""
menuMore = "Mehr"
readMore = "Mehr"
readOtherPosts = "Lese andere Posts"
newerPosts = "Neue Posts"
olderPosts = "Alte Posts"
missingContentMessage = "Seite nicht gefunden..."
missingBackButtonLabel = "ZurÃ¼ck zur Hauptseite"
minuteReadingTime = "Lesezeit (min)"
words = "WÃ¶rter"
sponsorsTitle = "Sponsoren"

[languages.de.params.logo]
logoText = "ZSM-Sat Team"
logoHomeLink = "/de"

[languages.de.menu]

[[languages.de.menu.main]]
identifier = "about"
name = "Ãœber uns"
url = "/de/about"

# POLISH
[languages.pl]
languageCode = "pl-PL"
languageName = "ðŸ‡µðŸ‡± Polski"
title = "ZSM-Sat Team"
weight = 1

[languages.pl.params]
subtitle = ""
owner = ""
keywords = ""
copyright = ""
menuMore = "PokaÅ¼ wiÄ™cej"
readMore = "Czytaj wiÄ™cej"
readOtherPosts = "WiÄ™cej wpisÃ³w"
newerPosts = "Nowsze wpisy"
olderPosts = "Starsze wpisy"
missingContentMessage = "Nie znaleziono strony..."
missingBackButtonLabel = "WrÃ³Ä‡ do strony gÅ‚Ã³wnej"
minuteReadingTime = "min."
words = "sÅ‚."
sponsorsTitle = "Sponsorzy"

[languages.pl.params.logo]
logoText = "ZSM-Sat Team"
logoHomeLink = "/pl"

[languages.pl.menu]

[[languages.pl.menu.main]]
identifier = "about"
name = "O nas"
url = "/pl/about"

# ENGLISH

[languages.en]
languageCode = "en-US"
languageName = "ðŸ‡ºðŸ‡¸ English"
title = "ZSM-Sat Team"
weight = 2

[languages.en.params]
subtitle = ""
owner = ""
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"
sponsorsTitle = "Sponsors"

[languages.en.params.logo]
logoText = "ZSM-Sat Team"
logoHomeLink = "/en"

[languages.en.menu]

[[languages.en.menu.main]]
identifier = "about"
name = "About us"
url = "/en/about"

[markup.goldmark.renderer]
unsafe = true